### PR TITLE
Correctly detect attr binary during tests

### PR DESCRIPTION
**Pull request by benrubson**
Hello,

This issue should solve issue #329 as Mac OS uses `xattr` command instead of `attr`.

Ben

### CODE REVIEW

**Comment by benrubson** [comment]
@rfjakob I think you can safely merge this and close #329 :)
Thank you again 👍

**Comment by benrubson** [comment]
More generic version which now also supports FreeeBSD.
FreeBSD uses `lsextattr` binary.
However, it also uses different includes to support xattr, which are not yet implemented by encfs.

**Comment by benrubson** [comment]
@rfjakob let's merge this one and close #329 ?
Thank you (again) 👍 
Ben

**Comment by benrubson** [comment]
@rfjakob what about this one (and then close #329) ?
Thank you again for your support 👍 
Ben

**Comment by rfjakob** [comment]
Hmm the commit message does not match what the patch does. What is the "V" command line argument?

**Comment by benrubson** [comment]
It shows the encfs version, to which I added compilation options (`HAVE_XATTR`).
This flag is then used by reverse test to know if encfs has `HAVE_XATTR` or not.

**Comment by rfjakob** [comment]
I have commited the part that detects the attr binary as 8d8506f2eb1d7aa0cec1c4fb6eff11273b950b9b .

I'm not sure about the "detect if we were built without xattr support" part, but in any case, this would be a separate commit.

**Comment by benrubson** [comment]
Thank you very much @rfjakob.
I'll then submit another PR for the builds without xattr support.
(as for example FreeBSD builds are made without xattr support)

**Pull request closed without merging**
