### PR TITLE
Make all xattr operations on link themselves

### PR DESCRIPTION
**Pull request by benrubson**
Hello,

This PR finishes works done in #287 making all xattr operations on links themselves instead of their targets.
It should also solve #341 using `XATTR_NOFOLLOW` Mac OS flag.

Thank you 👍 

Ben

### CODE REVIEW

**Comment by rfjakob** [comment]
Hi Ben, thanks for the patch. It looks like Linux does not have XATTR_NOFOLLOW - is this handled in your code?

Also, I would really like to see a testcase in normal.t.pl added for this.

**Comment by benrubson** [comment]
`XATTR_NOFOLLOW ` is only used if `XATTR_ADD_OPT` is defined, it will be added as the last option to xattr functions.
Linux does not define `XATTR_ADD_OPT`, so will not use `XATTR_NOFOLLOW` 👍

**Comment by benrubson** [comment]
Regarding the test case, I think the one added in reverse.pl in #287 does the job ?

**Comment by rfjakob** [comment]
Yes the test is a good improvement, but writing xattrs should also be
tested. If i saw it correctly the test only checks reading, right?

**Comment by benrubson** [comment]
I think we're ready to merge @rfjakob 👍

**Comment by benrubson** [comment]
@rfjakob let's commit this please ?
I'll then be able to re-arrange #338.
Thank you very much 👍

**Comment by rfjakob** [comment]
Sorry, I will be focusing completely on #214 for now. This affects multiple users on multiple platforms. Debian 9 was just released that includes EncFS 1.9.1. We should give it all we got.

**Comment by benrubson** [comment]
I totally agree, #214 must really be corrected.
If you plan to release 1.9.2, once #214 solved, I propose to come back to this (#342), as well as #295 which makes the code handling errors better.
This would make a nice 1.9.2 :)
Many thx @rfjakob 👍

**Comment by mouse07410** [comment]
Could you tell me if there's any reason this PR hasn't been merged?

**Comment by benrubson** [comment]
@mouse07410, @rfjakob who has the merge right is focusing on an even worst bug, #214.
Once solved he should review & merge this one :)

**Comment by benrubson** [comment]
Perhaps you now have some time to see this tiny change @rfjakob ?
Many thx 👍

**Comment by benrubson** [comment]
Shall we go with this one @rfjakob ?
Thank you very much for your support 👍

**Comment by rfjakob** [comment]
Tests fail on my Fedora box:
```
$ g++ --version
g++ (GCC) 7.1.1 20170622 (Red Hat 7.1.1-3)

$ ./test.sh 
tests/normal.t.pl ... 
runTests: mode=standard
tests/normal.t.pl ... 4/122 attr_set: Operation not supported
Could not set "encfs" for /tmp/encfs-tests-iEas/crypt/data

#   Failed test 'extended attributes can be set (return code was 256)'
#   at tests/normal.t.pl line 324.
#          got: '256'
#     expected: '0'
attr_get: Operation not supported
Could not get "encfs" for /tmp/encfs-tests-iEas/crypt/data

#   Failed test 'extended attributes can be get (return code was 256)'
#   at tests/normal.t.pl line 326.
#          got: '256'
#     expected: '0'
attr_get: No data available
Could not get "encfs" for /tmp/encfs-tests-iEas/crypt/data-rel
tests/normal.t.pl ... 57/122 
runTests: mode=paranoia
tests/normal.t.pl ... 67/122 attr_set: Operation not supported
Could not set "encfs" for /tmp/encfs-tests-HoSG/crypt/data

#   Failed test 'extended attributes can be set (return code was 256)'
#   at tests/normal.t.pl line 324.
#          got: '256'
#     expected: '0'
attr_get: Operation not supported
Could not get "encfs" for /tmp/encfs-tests-HoSG/crypt/data

#   Failed test 'extended attributes can be get (return code was 256)'
#   at tests/normal.t.pl line 326.
#          got: '256'
#     expected: '0'
attr_get: No data available
Could not get "encfs" for /tmp/encfs-tests-HoSG/crypt/data-rel
tests/normal.t.pl ... 120/122 # Looks like you failed 4 tests of 122.
tests/normal.t.pl ... Dubious, test returned 4 (wstat 1024, 0x400)
Failed 4/122 subtests 
	(less 2 skipped subtests: 116 okay)
tests/reverse.t.pl .. ok     

Test Summary Report
-------------------
tests/normal.t.pl (Wstat: 1024 Tests: 122 Failed: 4)
  Failed tests:  18-19, 81-82
  Non-zero exit status: 4
Files=2, Tests=147, 23 wallclock secs ( 0.04 usr  0.01 sys + 20.10 cusr  0.39 csys = 20.54 CPU)
Result: FAIL
Failed 1/2 test programs. 4/147 subtests failed.
```

**Comment by benrubson** [comment]
Does your `/tmp` have `user_xattr` ?

**Comment by rfjakob** [comment]
Fedora mounts a tmpfs to /tmp, and it looks like tmpfs does not support user_xattr:
```
0 jakob@brikett:/tmp$ attr -s user.abc -V def foo
attr_set: Operation not supported
Could not set "user.abc" for foo
```
This means xattr testing must move to /var/tmp

**Comment by benrubson** [comment]
Do you think we should modify this in both pl test scripts ?
`my $tempDir = $ENV{'TMPDIR'} || "/tmp";`
to
`my $tempDir = "/var/tmp";`
?

**Comment by rfjakob** [comment]
I have limited it do Linux like this: https://github.com/vgough/encfs/pull/356/commits/9a169bfb78f4249120ea971aaff5e5a8307b5697#diff-6b2afe0bcb135d3fd0af455eb74bdd65R15

Looks better now, however, I get some `Could not get ...` messages:
```
$ ./test.sh 
tests/normal.t.pl ... 
runTests: mode=standard
tests/normal.t.pl ... 1/122 attr_get: No data available
Could not get "encfs" for /var/tmp/encfs-tests-25n0/crypt/data-rel
tests/normal.t.pl ... 55/122 
runTests: mode=paranoia
tests/normal.t.pl ... 69/122 attr_get: No data available
Could not get "encfs" for /var/tmp/encfs-tests-tvlS/crypt/data-rel
tests/normal.t.pl ... ok       
tests/reverse.t.pl .. ok     
All tests successful.
Files=2, Tests=147, 22 wallclock secs ( 0.05 usr  0.00 sys + 20.18 cusr  0.39 csys = 20.62 CPU)
Result: PASS
```

**Comment by rfjakob** [comment]
Yes, these also appear in Travis: https://travis-ci.org/vgough/encfs/jobs/258947994#L852

Why doesn't "make check" report this?

**Comment by benrubson** [comment]
The `Could not get ...` messages are expected :
```
$return_code = ($have_xattr) ? system(@getattr, "$crypt/data-rel") : 1;
isnt($return_code, 0, "extended attributes operations do not follow symlinks (return code was $return_code)");
```
On Linux, we can't set extended attributes on symlinks (FreeBSD allows this).
So to check that symlinks are not followed when attributes are set/get, this test checks that it does not get the attribute of the link's target :)

`make check` only outputs the failed tests (proper / easier to read output).

**Comment by benrubson** [comment]
> `make check` only outputs the failed tests (proper / easier to read output).

Thanks to `--output-on-failure` in `CMakeLists.txt`.

**Comment by benrubson** [comment]
I think the following would then need to be updated due to the `/var/tmp` tweak :
https://github.com/vgough/encfs/blob/master/test.sh#L7
`grep -E "(/var)?/tmp/encfs-reverse-tests-|(/var)?/tmp/encfs-tests-"`

Regarding `Could not get ...` messages, they are "expected" :
```
$return_code = ($have_xattr) ? system(@getattr, "$crypt/data-rel") : 1;
isnt($return_code, 0, "extended attributes operations do not follow symlinks (return code was $return_code)");
```
On Linux, we can't set extended attributes on symlinks (FreeBSD allows this).
So to check that symlinks are not followed when attributes are set/get, this test checks that it does not get the attribute of the link's target :)

**I then think we should add `2>/dev/null` to this specific test.**

Regarding `make check`, it only outputs the failed tests (proper / easier to read output, especially when they are pasted into bug reports).
So this thanks to `--output-on-failure` in `CMakeLists.txt`.

**I then think `./test.sh` here is redundant :**
https://github.com/vgough/encfs/blob/master/.travis.yml#L28

Last thing I noted (not really related to this PR) :
Here we have verbose :
https://github.com/vgough/encfs/blob/master/CMakeLists.txt#L272
Here we have debug :
https://github.com/vgough/encfs/blob/master/test.sh#L16
Not sure which one we should adopt, but we could standardize :)

Thank U Jakob 👍

**Comment by rfjakob** [comment]
@benrubson This --output-on-failure` thing does not seem to work properly. Check out https://github.com/vgough/encfs/issues/358 , there is zero useful info in the output.

**Comment by benrubson** [comment]
The command to use to have the failed output is `make check` as now described in `INSTALL.md` file :)
Not `make test` as @svetlemodry used in #358 :)

**Comment by rfjakob** [comment]
Ok. Why do we have both?

**Comment by benrubson** [comment]
Unfortunately you can't modify CMake test target to output errors.
This is why we have our own check target.
I added it when I added the Perl tests to the CMake file (#309), to be able to run everything with the make command :)

**Comment by rfjakob** [comment]
Hmm that's too bad and pretty confusing for users. Maybe we should drop both `make test` and `make check` and have just `test.sh`. People will keep running `make test` all the time!

**Comment by rfjakob** [comment]
Merged as https://github.com/vgough/encfs/pull/356

**Pull request closed without merging**
