### PR TITLE
 Add ability to disable file data encoding

### LINKED ISSUE #481: Encrypt filenames only / use nullCipher for data
Hi,

Would be nice to be able to encrypt filenames only.
Useful if files' content is already encrypted (whatever the method is), but goal is also to have filenames encrypted.
EncFS should then be able to use nullCipher for data itself.

Thank you 👍 

Ben

### PR DESCRIPTION
**Pull request by benrubson**
Hi,

This PR closes #481 adding the ability to disable file data encoding a FS creation.
Note that this must be enabled by adding the new option `--unsafe`.
And must be enforced at mount by `--unsafe`.
User then knows !

Many thx 👍 

Ben

### CODE REVIEW

**Comment by benrubson** [comment]
Modifications done @rfjakob 👍 
Thank you for your review.

Regarding example filesystems, we do not have such "feature" in EncFS (yet) ?
Or perhaps I missed something ? :)
Thank you !

**Comment by rfjakob** [comment]
Regarding example filesystems, you just create a filesystem and add it to the source code!

**Comment by benrubson** [comment]
Perhaps this should be part of a new PR, which would provide an example per filesystem (as we don't have this yet) exhaustively ?

**Comment by rfjakob** [comment]
Ok!

**Comment by benrubson** [comment]
Thx 👍

**Comment by rfjakob** [comment]
Travis seems unhappy, though:

> integration/reverse.t.pl .. 11/46 sh: line 1:  2269 Segmentation fault: 11  ENCFS6_CONFIG=/var/folders/bb/n7t3rs157850byt_jfdcq9k80000gn/T//encfs-reverse-tests-YOAV/plain/.encfs6.xml ./build/encfsctl cat --extpass="echo test" --reverse /var/folders/bb/n7t3rs157850byt_jfdcq9k80000gn/T//encfs-reverse-tests-YOAV/plain hello.txt > /var/folders/bb/n7t3rs157850byt_jfdcq9k80000gn/T//encfs-reverse-tests-YOAV/plain/helloenc.txt

**Comment by benrubson** [comment]
Yep see #492 :-|

**Pull request merged**
