### PR TITLE
Improve logging

### PR DESCRIPTION
**Pull request by benrubson**
Hello,

This PR solves #270.

Many thanks 👍 

Ben

### CODE REVIEW

**Comment by benrubson** [comment]
@vgough @rfjakob, could we flag this in project `1.9.2 release` please ?
Many thanks 👍

**Comment by rfjakob** [comment]
I like getting rid of the date in daemon mode and adding colors in the foreground.
I'm not sure about the addition of "-u". Info about the user should be collected by syslog, and journald already does that pretty well. Also, ELPP_INITIALIZE_SYSLOG looks scary :)

I'd ask you to
1) Get rid of "-u"
2) Have all changes in a single commit that describes what it does (that is, mention both the removal of the date in daemon mode and the addition of colors)

**Comment by benrubson** [comment]
Thank you for your feedback @rfjakob 👍 

> Info about the user should be collected by syslog, and journald already does that pretty well.

Mmmmh unfortunately [FreeBSD syslog](http://www.unix.com/man-page/FreeBSD/5/syslog.conf/) does not provide the ability to add username to generated messages.
Perhaps you were thinking about another way to do it ?

> Also, ELPP_INITIALIZE_SYSLOG looks scary :)

Why ? :) This is a documented [Easylogging feature](https://github.com/muflihun/easyloggingpp#syslog) :)

Encfs is used by many users on some of my servers, so having the username in error messages is really helpful.

**Comment by benrubson** [comment]
@rfjakob perhaps instead of `-u` you would prefer `-t` to specify an alternate syslog tag ?
We would then be able to add `-t encfs/myuser`, or `-t encfs.fsdata`, or anything else we want...
As an example this feature has been implemented [into Apache](https://httpd.apache.org/docs/trunk/mod/core.html#errorlog).

**Comment by rfjakob** [comment]
Yes, `-t` is much better.

It also avoids allocating a buffer whose size you don't know in advance. Can you really do this in C++ !?
```
char ident[5 + 1 + strlen(pw->pw_name) + 1];
```

**Comment by benrubson** [comment]
OK @rfjakob, perfect, thank you for your feedback 👍

**Comment by benrubson** [comment]
See #296 for a one-commit PR.
Thx !

**Pull request closed without merging**
