### PR TITLE
update readpassphrase

### PR DESCRIPTION
**Pull request by vgough**
@benrubson This updates readpassphrase to the latest version I've found in a quick search.  I made a couple changes over the original:

* build as C++
* adjust include, add path.h include
* change NULL -> nullptr
* reformat with clang-format

### CODE REVIEW

**Comment by benrubson** [comment]
Clang-tidy complains a lot regarding this new version :)
And I think it should also complain (when some warnings will have been corrected ?) about the 2 `(void)write(...)`.

**Comment by vgough** [comment]
There are still lots of clang-tidy complaints throughout encfs.   Looks like most of the complaints in readpassphrase are readability-implicit-bool-cast and readability-braces-around-statements, neither of which bother me much for imported C code.

I don't see any clang-tidy or compiler complaints about `(void)write`, so not sure what you're expecting.

**Comment by benrubson** [comment]
Sorry, these `(void)write` warnings are not triggered by clang but by gcc... My mistake...
Taken from log given in #407 :
```
/home/makerpm/rpmbuild/BUILD/encfs-master/encfs/readpassphrase.cpp:128:46: warning: ignoring return value of 'ssize_t write(int, const void*, size_t)', declared with attribute warn_unused_result [-Wunused-result]
   (void)write(output, prompt, strlen(prompt));
                                              ^
/home/makerpm/rpmbuild/BUILD/encfs-master/encfs/readpassphrase.cpp:149:33: warning: ignoring return value of 'ssize_t write(int, const void*, size_t)', declared with attribute warn_unused_result [-Wunused-result]
     (void)write(output, "\n", 1);
                                 ^
```

I then would like to correct this, so that these warnings do not bother users anymore.
Thus I opened PR #424 (which I just updated with the log above to clarify).

For sure clang-tidy complaints regarding the new readpassphrase version are not so important, but I think it would be interesting to have clang-tidy to warn as less as possible, to easily detect future code mistakes. This is why I opened #427 (as well as #426), to try to make an effort to correct clang-tidy & compilation warnings.

Many thanks 👍

**Comment by samrocketman** [comment]
@vgough this PR would be more appropriate as two commits because you're copying code.  1 commit for the original and 1 commit for your explicit changes.  This way your changes are more obviously documented because I can't tell what is your changes and what is the original copy at first glance.

**Pull request closed without merging**
