### PR TITLE
make encfssh script executable

### LINKED ISSUE #224: encfssh not executable
Please add exec bit to encfssh script.

### PR DESCRIPTION
**Pull request by rogeliodh**
make encfssh executable
<br />
<br />Fixes #224

### CODE REVIEW

**Comment by samrocketman** [comment]
+2

**Comment by rfjakob** [comment]
Obviously-good change, merging.

**Comment by kyrios123** [comment]
FYI - I Just installed v1.9.2 and encfssh is **not** executable

**Comment by rfjakob** [comment]
Hmm. Looks good to me:

```
$ git clone https://github.com/vgough/encfs.git
$ cd encfs/
$ git describe
v1.9.2
$ ls -l encfs/encfssh
-rwxr-xr-x  1 me  me  2409 Jul 26 14:26 encfssh
```

**Comment by kyrios123** [comment]
just download the archive: https://github.com/vgough/encfs/archive/v1.9.2.tar.gz
uncompress the tarball -> check the file, it's executable.
* cmake
* make
* make install

-> Installed version is not executable.

**Comment by rogeliodh** [comment]
@kyrios123 I've submitted a new PR #352 to fix this

**Comment by kyrios123** [comment]
@rogeliodh super, thanks a lot !

**Pull request merged**
