### PR TITLE
Lots of lint fixes from clang-tidy

### PR DESCRIPTION
**Pull request by vgough**
Almost all automated clang-tidy fixes, with the exception of one possible NPE detected by lint.

### CODE REVIEW

**Comment by benrubson** [comment]
Could we think about #295 first so that I will not have to rebase it entirely ?
Many thanks Valient 👍 
And glad to see you're back :)

**Comment by vgough** [comment]
Sorry, github only showed me your comment after I clicked 'merge'.  I didn't realize how extensive your PR was.  Let me review your PR, if it's ready to go then we can revert this temporarily.

**Comment by benrubson** [comment]
Thank you very much :)
I'll then answer your questions in your review 👍

**Comment by samrocketman** [comment]
Yes, welcome back!

**Pull request merged**
