### PR TITLE
Update cmake

### PR DESCRIPTION
**Pull request by benrubson**
Hello,

Here is a PR which update cmake prerequisites, see #303.

Thx 👍 

Ben

### CODE REVIEW

**Comment by benrubson** [comment]
@rfjakob and this one ? :) Thx 👍

**Comment by benrubson** [comment]
@rfjakob, what about merging this PR please ?
Many thanks 👍

**Comment by rfjakob** [comment]
Problem here is that you cannot build on debian stable anymore. I don't know, but there should be a better solution

**Comment by benrubson** [comment]
Strange, do you have a debian stable build log ?

**Comment by rfjakob** [comment]
No, but Debian stable has cmake 3.0.2 ( https://packages.debian.org/jessie/cmake ). I think the goal should be to make it "just work" there.

**Comment by benrubson** [comment]
It will build with cmake 3.0.2, cmake 3.2.0 is just an "advice" to run configuration flawlessly (it correctly detects Intl etc...).
In addition, next stable Debian (which should come shortly) has cmake 3.7.
And you can backport cmake 3.6 on Jessie 👍

**Comment by rfjakob** [comment]
Why doesn't it run flawlessly on cmake 3.0.2? Is the encfs build process so special?

**Comment by benrubson** [comment]
cmake 3.0.2 does not detect Intl, leading to :
```
CMake Warning at CMakeLists.txt:131 (find_package):
  Could not find module FindIntl.cmake or a configuration file for package
  Intl.
  Adjust CMAKE_MODULE_PATH to find FindIntl.cmake or set Intl_DIR to the
  directory containing a CMake configuration file for Intl.  The file will
  have one of the following names:
    IntlConfig.cmake
    intl-config.cmake
```

Whereas cmake >= 3.2.0 detects it, which is better, no error output.

**Comment by rfjakob** [comment]
And if we ship the file FindIntl.cmake with encfs?

**Comment by benrubson** [comment]
Seems as a bad workaround to me, as we would have to maintain this "external" file :|
It will still build with cmake 3.0.2, you will simply get an advice to run a newer version :
```
+if (${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION} LESS 3.2)
+  message(WARNING "You should use cmake 3.2.0 or newer for configuration to run correctly.")
+endif()
```

**Comment by rfjakob** [comment]
Looks pretty compact: https://github.com/Kitware/CMake/blob/master/Modules/FindIntl.cmake
Maybe we can pull it into the cmake config file?

**Comment by rfjakob** [comment]
No, probably better to keep it a separate file.

I mean, we ship our own copies of tinyxml and easylogging to make it easy to build encfs. We should continue to try making it easy.

**Comment by benrubson** [comment]
According to previous releases, Debian Stretch should be there in June or July.
https://wiki.debian.org/DebianStretch
Then, what about moving to 3.2.0 (with 3.0.2 (and lower !) still usable) ?

**Comment by rfjakob** [comment]
Haha, no, encfs is 10 years old, we shouldn't need a not-yet-released distro to compile it without errors

**Comment by benrubson** [comment]
Should be OK now @rfjakob 👍 
It correctly runs with cmake 3.0.2, and this is now the minimum version advised (in cmake configuration file and INSTALL.md).
However, I give Travis cmake 3.1.0, as it is the first x86_64 compiled version.

**Comment by benrubson** [comment]
What about this @rfjakob ?
Many thx 👍

**Comment by benrubson** [comment]
Should be even better now @rfjakob 👍 
It correctly runs with cmake 3.0.2, and this is now the minimum version advised (in cmake configuration file and INSTALL.md).
I also give Travis cmake version 3.0.2. As this x86_64 compiled version is not available online, I compiled it and pushed it to the repository.
Thank you 👍

**Comment by rfjakob** [comment]
Thanks ben, i'm currently travelling abroad, i'll be back next week and
will try to merge this

**Comment by benrubson** [comment]
@rfjakob, just to remind you this PR :)
Many thx 👍

**Comment by benrubson** [comment]
@rfjakob do you think we could merge this PR ?
Thank you very much for your help 👍

**Comment by benrubson** [comment]
Many thanks @rfjakob 👍

**Comment by benrubson** [comment]
Mmmmh sounds like CircleCI is failing, I did not notice we used both Travis and CircleCI.
Do you know why we use both of them ?
Perhaps we could remove CircleCI ?

**Comment by rfjakob** [comment]
I'm not sure why we have both, probably because Travis could not run FUSE tests at some point?

But I'd rather have the failure fixed than removing the tests. It's an additional platform that is tested, after all.

**Comment by benrubson** [comment]
I think we should then `make check` instead of `make test` :
https://github.com/vgough/encfs/blob/master/circle.yml#L13

**Comment by benrubson** [comment]
#327 should at least help us.

**Comment by benrubson** [comment]
OK we now have some more output regarding failing tests in CircleCI, perfect.
CircleCI does not seem to be correctly configured, at least as Travis is (no `modprobe fuse` etc...).
Certainly this is why it is failing.

**Pull request merged**
