### PR TITLE
Bump FUSE_USE_VERSION to 29

### PR DESCRIPTION
**Pull request by benrubson**
Hi,

Related to #328, let's test bumping FUSE_USE_VERSION to 29 to see if all our CI tests run correctly (especially the Mac OS one).

Ben

### CODE REVIEW

**Comment by benrubson** [comment]
OK so tests pass correctly, we could then perhaps think about merging this in order to use the last 2.x Fuse lib series.

**Comment by benrubson** [comment]
@rfjakob any thoughts on this ?
Sounds quite reasonable to me (as mentioned in #328, even Debian Wheezy (oldoldstable, may 2013) has libfuse 2.9).
vgough seems to be OK according to his comment there.
Thx 👍

**Comment by rfjakob** [comment]
I'm a bit worried about osxfuse. Their implementation has always been way more brittle, and maybe there is a reason they kept their default at version 26?

**Comment by benrubson** [comment]
I've asked @bfleischer, [osxfuse](https://github.com/osxfuse/osxfuse) maintainer, to give us his feedback 👍

**Comment by bfleischer** [comment]
FUSE for macOS 3.x has been shipping with lib(osx)fuse 2.9.x since May 2015. I'm not aware of compatibility issues.

Defining `FUSE_USE_VERSION` to 29 instead of 26 should make no difference at all. If I have not overlooked something there is not even a version check in libfuse that differentiates between version 26 and 29.

> I'm a bit worried about osxfuse. Their implementation has always been way more brittle, and maybe there is a reason they kept their default at version 26?

What do you mean by "brittle"? FUSE for macOS ships with two versions of the FUSE library:

* libosxfuse 2.9.7: This is the default FUSE library on macOS. I know the renaming is not ideal, but it was necessary to keep binary compatibility with old MacFUSE file systems.
* libfuse 2.7.4: This is the MacFUSE compatibility layer needed to support legacy MacFUSE file systems. It is only available if the user selected this option during the install. No new file systems should be linked against this library.

**Comment by benrubson** [comment]
> FUSE for macOS 3.x has been shipping with lib(osx)fuse 2.9.x since May 2015.

This is the one we use, at least in our CI environment :
```
brew cask install osxfuse
(...)
Downloading https://github.com/osxfuse/osxfuse/releases/download/osxfuse-3.5.8/osxfuse-3.5.8.dmg
```

Perfect, thank you very much for your comment @bfleischer, really appreciated 👍

**Comment by samrocketman** [comment]
I realize I'm a bit late to this discussion and I do not recommend chsnging history.  However, going forward I would prefer changes like this to be rebased.  6 commits to change one line is a bit much.  Rebasing would have discarded all of the merge commits.  Just some food for thought on my workflow preference.

**Comment by benrubson** [comment]
"Squash & merge" has been used to make master history clean, keeping only one global entry 👍

**Pull request merged**
