### PR TITLE
Correct performance warnings

### PR DESCRIPTION
**Pull request by benrubson**
Hi,

This PR helps solving #427, correcting :

```
DirNode.cpp:423:41: warning: string concatenation results in allocation of unnecessary temporary strings; consider using 'operator+=' or 'string::append()' instead [performance-inefficient-string-concatenation]
      string newFull = sourcePath + '/' + newName;
                                        ^
```
_here it disables the Clang test_

However, I'm not sure how to handle this one :
```
FileUtils.cpp:500:58: warning: the parameter 'data' is copied for each invocation but only used as a const reference; consider making it a const reference [performance-unnecessary-value-param]
                              std::vector<unsigned char> data) {
                                                         ^
```

Edit : just found a way, please **review with care** !

Thx 👍 

Ben

### CODE REVIEW

**Comment by rfjakob** [comment]
Unsure about these changes. Looks like we lose a lot of readability.

Compare

       string plainPath = volumeDir + name;

With

       string plainPath = string(volumeDir).append(name);

**Comment by benrubson** [comment]
Goal was to conform to clang rules to get rid of the warnings.
We also get rid of some temporary buffers using append().
We could try to use += to increase readability ? However I'm not sure it would really help.
Lines of code are a little bit longer, but still readable IMO, and almost limited to one file (DirNode.cpp).

**Comment by benrubson** [comment]
What about the second commit ?
OK with it @rfjakob ?
Thx 👍

**Comment by rfjakob** [comment]
"Correct unnecessary-value-param" looks good to me

**Comment by benrubson** [comment]
Thx for your review 👍 
So what about this whole PR ?
Would you be ready to make a small concession on readability (in almost only one file) to correct warnings ?

**Comment by rfjakob** [comment]
To be honest, I see the downside (more complicated code), but I don't see the upside yet. How many % performance do we gain?

**Comment by benrubson** [comment]
Of course hard to measure, almost nothing I would say.
Primary goal is to get ride of all compilation & clang warnings, so that we have a clear build log, making it easier to check if there are new warnings when a PR / new code is submitted / merged.

**Comment by rfjakob** [comment]
I think the situation would be different if this was a correctness problem. But as this is only a performance warning, I suggest to turn the warning off.

**Comment by rfjakob** [comment]
(I agree with your goal of getting the code warning-free!)

**Comment by benrubson** [comment]
I like when we disable as least tests as possible, but OK, let's then disable `performance-inefficient-string-concatenation`.

**Comment by benrubson** [comment]
OK, PR updated 👍

**Pull request merged**
