### PR TITLE
Changes for 1.8.1

### PR DESCRIPTION
**Pull request by rfjakob**
One thing that may be debateable is that I have disabled uniqueIV for reverse mode by default (added in v1.8). It can still be enabled through expert mode. I have explained the details in commit 21b3811f86d0803c30bd3baee34e1769d06597b1 , but it boils down to that it may be an unexpected change for users, and cause regressions for them, just like disabling the cache did.

### CODE REVIEW

**Comment by vgough** [comment]
Nice, thanks Jakob!

**Comment by samrocketman** [comment]
This is great!  I'm glad to see the project continue.

**Comment by rfjakob** [comment]
:)
Valient, I'd like to release 1.8.1, this time including the configure script in the tarball. You ok with that?

**Comment by vgough** [comment]
Sure, although I don't think it is unreasonable to expect those building from source to be able to generate the configuration file, but I realize that autoconf can be messy.

Please document somewhere how you created the tarball, so it can be done consistently in future releases.

**Comment by rfjakob** [comment]
Yes, otoh, this bug report is where the idea came from:
https://github.com/vgough/encfs/issues/65
I thought including the configure script in release tarballs will avoid a
lot of headache for our users. I will script the process.
If you want to build master, you'd still need autoconf.

**Pull request merged**
