### PR TITLE
Read config into memory and pass its content to tinyxml2 (#253)

### PR DESCRIPTION
**Pull request by johbo**
Trying to address issue #253.

From investigating the comments I found that it seems to be best to read the configuration file into memory first and then pass the content to tinyxml2, using `XmlDocument.Parse()` instead of `XmlDocument.LoadFile()`.

### CODE REVIEW

**Comment by johbo** [comment]
Also tried to add a test  for this problem, but it seems that I did not yet get it quite right: https://github.com/johbo/encfs/commit/59b571a5e33195bbd85ebf18c57a96233e980d70

I did observe this output which seems to be caused by the added test:

```
  Parse errors: Tests out of sequence.  Found (49) but expected (50)
                Tests out of sequence.  Found (50) but expected (51)
                Tests out of sequence.  Found (51) but expected (52)
                Tests out of sequence.  Found (52) but expected (53)
                Tests out of sequence.  Found (53) but expected (54)
Displayed the first 5 of 60 TAP syntax errors.
```

**Comment by benrubson** [comment]
You also have to increase counter at line 5 of `tests/normal.t.pl` by the number of tests you add.

**Comment by johbo** [comment]
Thanks for the hint. I've also noticed that I did get into some extra trouble because one of the calls to `ok` was running inside of the child process. Seems this did confuse the test runner. After changing these bits it did at least pass on my debian box.

**Comment by rfjakob** [comment]
Looks good to me.

**Pull request merged**
